# Site settings
title: Mauricio Araya V.
long_title: Computer engineer, infrastructure specialist and freedom advocate
email: hello@mauricioaraya.net
description:  "DevOps, Infrastructure Automation, Linux and any related technology. Here is where I write
my thoughts about technology"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://mauricioaraya.net"
#url: "http://localhost:4000"
twitter_username: mabrizio
github_username:  mabrizio
linked_in: https://www.linkedin.com/in/mauricioaraya
github: https://github.com/mabrizio
# Build settings
markdown: kramdown

job:
  employer_name: POSSIBLE
  url: http://www.possible.com
  position: System Adminitrator/DevOps

noindex: true

sass:
  style: compressed
gems:
  - jekyll-redirect-from
# GitHub
safe: true
lsi: false
permalink: /:categories/:title.html
