# Site settings
title: Mauricio Araya V.
long_title: Computer engineer, infrastructure specialist and freedom advocate
email: hello@mauricioaraya.net
description:  "DevOps, Infrastructure Automation, Linux and any related technology. Here is where I write
my thoughts about technology"
baseurl: "" # the subpath of your site, e.g. /blog/
#url: "http://mauricioaraya.net"
url: "http://localhost:4000"
twitter_username: mabrizio
github_username:  mabrizio

# Build settings
markdown: kramdown

noindex: true

sass:
  style: compressed
